# template will search the file and plaxe the file in destination, URL will be url of workstation Private IP address
- name: Create Config file
  ansible.builtin.template:
    src: ""{{TEMPLATE}}"
    dest: /tmp/job.xml

- name: Create
  community.general.jenkins_job:
    config: "{{ lookup('file'. '/tmp/job.xml') }}"
    name: "{{item}}"
    url: http://172.31.3.24:8080
    user : admin
    password: "{{jenkins_password}}"
