- name: Create Pipeline Jobs
  ansible.builtin.include_tasks: pipeline.yml
  loop:
    - {name: "frontend", dir: "CIPipeline"}
    - {name: "cart", dir: "CIPipeline"}
    - {name: "catalogue", dir: "CIPipeline"}
    - {name: "user", dir: "CIPipeline"}
    - {name: "shipping", dir: "CIPipeline"}
    - {name: "payment", dir: "CIPipeline"}
