- name: Create folder {{ item.dir }}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job.xml') }}"
    name: "{{item.name}}"
    url: http://172.31.3.24:8080
    user : admin
    password: "{{jenkins_password}}"
  loop:
    - CIPipelines
    -
- name: Create Pipeline Jobs
  ansible.builtin.include_tasks: pipeline.yml
  loop:
    - {name: "frontend", dir: "CIPipeline"}
    - {name: "cart", dir: "CIPipeline"}
    - {name: "catalogue", dir: "CIPipeline"}
    - {name: "user", dir: "CIPipeline"}
    - {name: "shipping", dir: "CIPipeline"}
    - {name: "payment", dir: "CIPipeline"}
