# template will search the file and plaxe the file in destination, URL will be url of workstation Private IP address

- name: Check if Job exists or not - {{item.dir}}/{{item.name}}
  ansible.builtin.shell: java -jar /opt/jenkins-cli.jar -auth admin:{{jenkins_password}} -s http://172.31.7.18:8080 -webSocket get-job {{item.dir}}/{{item.name}}
  register: out
  ignore_errors: yes

- name: Create Config file - {{item.dir}}/{{item.name}}
  ansible.builtin.template:
    src: s-job.xml
    dest: /tmp/s-job.xml
  when: out.rc == 3

- name: Create Job - {{item.dir}}/{{item.name}}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/s-job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.7.18:8080
    user: admin
    password: "{{jenkins_password}}"
  when: out.rc == 3




#- name: Create Config file
#  ansible.builtin.template:
#    src: s-job.xml
#    dest: /tmp/s-job.xml
#
#- name: Create
#  community.general.jenkins_job:
#    config: "{{ lookup('file', '/tmp/s-job.xml') }}"
#    name: "{{item.dir}}"
#    url: http://172.31.3.24:8080
#    user : admin
#    password: "{{jenkins_password}}"
